---
- hosts: docker_hosts
  become: yes
  roles:
    - name: docker
      tags:
        - docker
    - name: geerlingguy-swap
      tags:
        - swap
    - name: geerlingguy-letsencrypt
      tags:
        - ssl
    - name: dms
      tags:
        - dms
