---
- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages for Docker
  apt: name={{ docker_required_packages }} state=latest update_cache=yes

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: yes

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install Docker
  apt: name={{ docker_packages }} state=latest update_cache=yes

- name: Install Python Docker module
  pip:
    name: docker

- name: Add adminstrator to docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: yes

- name: Ensure that /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Install Docker Compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x

- name: Install docker settings
  copy:
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
    content: |
      {
        "mtu": 1450
      } 
  notify: Restart Docker
